# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.7
  - 3.3
before_install:
  - pip install nose Sphinx
install:
  - true
script:
  - python setup.py test
